apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eheakwnzd-nodejs
  janus-idp.io/tekton: eheakwnzd-nodejs
  backstage.io/kubernetes-id: eheakwnzd-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eheakwnzd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
